### ISSUE TITLE
[FE] Homepage: CSP and no category icons on Mozilla-based browsers

### ISSUE THREAD

**Issue by mfortini** [teamdigitale/dati-semantic-frontend#458]
Category icons are missing
![image](https://github.com/teamdigitale/dati-semantic-frontend/assets/1104926/106f2034-2708-4fec-ac45-f34f512469eb)

This is the wayback machine's screenshot (https://web.archive.org/web/20231112153635/https://schema.gov.it/)
![image](https://github.com/teamdigitale/dati-semantic-frontend/assets/1104926/31bcd4e2-6d78-4c51-abb2-b1dc1c480590)

**Comment by mfortini** [comment]
Problem is related to CSP
![image](https://github.com/teamdigitale/dati-semantic-frontend/assets/1104926/561cec34-e389-48ad-98dc-9d3a611a2e8a)

https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

**Comment by Fupete** [comment]
⚠️ I would like to report that the problem is back if it had been fixed: no icons on Firefox. 

![screen](https://github.com/teamdigitale/dati-semantic-frontend/assets/6736103/468d8a01-dfcc-434a-ae3d-e35de042c099)

**Comment by mauropratesi** [comment]
CC: @Clou-dia. 
<img width="796" alt="Screenshot 2024-01-29 120220" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/24318d22-d728-435b-ae5c-08079d9d6b51">


The test was conducted using the Firefox browser on a PC, and indeed, the issue highlighted by the reported problem has been resolved. The screenshot refers to the PC device with the Firefox browser, but the same result is also observed with the following devices: iPad Mini, iPhone SE, Samsung Galaxy S20+, Samsung Galaxy S10/S10+. 
Tests on Safari and Brave browsers are yet to be conducted.

**Comment by mauropratesi** [comment]
<img width="415" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/e49af748-2751-470a-b87e-c834f26eba9c">


<img width="951" alt="image" src="https://github.com/teamdigitale/dati-semantic-frontend/assets/157471028/da2ea019-fb8f-4a6a-a9cd-aeec989ace43">

The test was conducted on the Firefox browser (v 122.0) on a Windows PC and not using BrowserStack.

**Comment by Fupete** [comment]
The indication of browserstack was just to reproduce the problem.... Neither MAC nor Windows (Firefox 121 or 122) on Browserstack (which I remind you are real devices) show icons. 

However, I confirm that several of our local devices Mac OS (Firefox 122) still do not show icons. 

iOS devices are ok.

**Comment by AgostinoPurificato** [comment]
Hello @Fupete ,
the tests was conducted using the "testedev" portal and not the production one.
The URL of "testedev" environment is: https://ndc-test.apps.cloudpub.testedev.istat.it/

Can you confirm that in this environment you can see the icons?

If everything is ok, the dev team will deploy the new version of the portal on production (schema.gov.it).

Thanks,
Agostino

**Comment by Fupete** [comment]
Ciao @AgostinoPurificato, 

I confirm that in the testdev environment the icons show up 💯
